name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Dockerfile build & test
      run: docker build -t lambda .
    
    - name: Validate cloudformtion template
      run: aws cloudformation validate-template --template-body file://cloudformation.yaml
      env:
        AWS_REGION: "us-west-1"

